### ISSUE TITLE
Not working on Windows 8.1

### ISSUE THREAD

**Issue by PhilAndrew** [FWeinb/node-atom-screenshot#2]
Uncaught exception
Error: connect EADRNOTAVAIL

My index.js
var fs = require('fs');
var screenshot = require('atom-screenshot');

screenshot({
  url : 'http://google.de',
  width : 1024,
  height : 768
})
.then(function(buffer){
  fs.writeFile('./out.png', buffer, function(err){
    screenshot.close();
  });
});

My package.json
{
  "name": "atomscreenshot",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "atom-screenshot": "^0.4.5"
  }
}

**Comment by FWeinb** [comment]
I removed the need for socket.io a while ago. Should work now.
